app/blog/models.py
from app import db

tags = db.Table('post_tag',
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
    db.Column('post_id', db.Integer, db.ForeignKey('post.id'))
)

class Base(db.Model):

    __abstract__  = True

    id          = db.Column(db.Integer, primary_key=True)
    title       = db.Column(db.String(255), nullable=False)
    slug        = db.Column(db.String(255), nullable=False, unique=True)

class Tag(Base):

    __tablename__ = 'tag'

    def __repr__(self):
        return self.title

class Post(Base):

    __tablename__ = 'post'

    description  = db.Column(db.String(255), nullable=False)
    perex        = db.Column(db.Text(), nullable=False)
    content      = db.Column(db.Text(), nullable=False)
    published_at = db.Column(db.DateTime, default=db.func.current_timestamp())
    modified_at  = db.Column(db.DateTime, default=db.func.current_timestamp(), nullable=True)
    tags         = db.relationship('Tag', secondary=tags, backref=db.backref('posts', lazy='dynamic'))

    def __repr__(self):
        return '<Post %r>' % (self.title)

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config.from_object('config')
db = SQLAlchemy(app)

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

@app.route('/', methods=['GET'])
def homepage():
    return render_template('homepage.html')

from app.blog.controllers import blog as blog_module

app.register_blueprint(blog_module)

db.create_all()

app/blog/controllers.py
from flask import Blueprint, abort, redirect, url_for, render_template
from datetime import datetime
from app import db, app
from app.blog.models import Post, Tag

blog = Blueprint('blog', __name__, url_prefix='/blog')

@blog.context_processor
def inject_now():
    return {'now': datetime.utcnow()}

@blog.route('/', methods=['GET'])
def index():
    articles = Post.query.all()
    return render_template('blog/index.html', posts=articles)

@blog.route('/stitok/<string:slug>', methods=['GET'])
def tag(slug):

    tag = Tag.query.filter_by(slug=slug).first()

    if tag is None:
        abort(404)

    articles = Post.query.filter(Tag.slug == slug)


    return render_template('blog/tag.html', posts=articles, tag=tag)


@blog.route('/<string:slug>', methods=['GET'])
def show(slug):

    article = Post.query.filter_by(slug=slug).first()

    if article is None:
        abort(404)

    return render_template('blog/show.html', post=article)

@blog.route('/<int:id>', methods=['GET'])
def short_link(id):

    article = Post.query.filter_by(id=id).first()

    if article is None:
        abort(404)

    return redirect(url_for('blog.show', slug=article.slug))

@blog.route('/rss.xml', methods=['GET'])
def rss():
    articles = Post.query.all()
    return render_template('blog/rss.xml', posts=articles), 200, {'Content-Type': 'application/rss+xml'}

app/templates/blog/article_list.html
<div class="article-list">
    {% for post in posts %}
    <article itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting">
      <header>
        <h2 itemprop="name headline">
          <a href="{{ url_for('blog.show', slug=post.slug) }}">{{ post.title }}</a>
        </h2>
        <p>
            <time pubdate datetime="{{ post.published_at.isoformat() }}" itemprop="datePublished" title="Zverejnené {{ post.published_at.strftime("%a, %d %b %Y %H:%M:%S") }}">{{ post.published_at.strftime("%a, %d %b %Y %H:%M:%S") }}</time>,
            {% if post.modified_at %}
            <time pubdate datetime="{{ post.modified_at.isoformat() }}" itemprop="dateModified" title="Naposledy upravené {{ post.modified_at.strftime("%a, %d %b %Y %H:%M:%S") }}">{{ post.modified_at.strftime("%a, %d %b %Y %H:%M:%S") }}</time>,
            {% endif %}
            <b>Štítky</b>:
            {% for tag in post.tags %}
                <a href="{{ url_for('blog.tag', slug=tag.slug) }}">{{ tag }}</a>{% if false == loop.last %}, {% endif %}
            {% endfor %}
          </p>
        <meta itemprop="description" content="{{ post.description }}">
      </header>
      <div class="content">
        {{ post.perex|safe }}
      </div>
      <p>
        <a itemprop="url" href="{{ url_for('blog.show', slug=post.slug) }}">Celý článok &rarr;</a>
      </p>
      </article>
      {% if loop.last is sameas false %}<hr>{% endif %}
      {% else %}
        <p>Žiaden príspevok.</p>
    {% endfor %}
  </div>

app/templates/blog/index.html
{% extends 'blog/layout.html' %}

{% block title %}Weblog{% endblock %}

{% block body %}
  <h1>Zoznam príspevkov</h1>
  {% include 'blog/article_list.html' with context %}
{% endblock %}

app/templates/blog/layout.html
<!DOCTYPE html>
<html lang="sk">
    <head prefix="og: http://ogp.me/ns# {% block ogp_namespace %}{% endblock %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="twitter:card" content="summary">
        <meta name="twitter:site" content="@jkucharovic">
        <meta name="twitter:creator" content="@jkucharovic">
        <meta property="og:locale" content="sk_SK">
        <meta property="og:url" content="{{ request.url }}">
        <meta property="og:title" content="{{ self.title() }}">
        {% block meta %}{% endblock %}
        {% if description %}
        <meta property="og:description" name="description" content="{{ description }}">
        {% endif %}
        <title>{% block title %}{% endblock %} | Jakub Kucharovic</title>
        {% block stylesheets %}
        <link rel="stylesheet" href="/assets/css/compiled.min.css">
        {% endblock %}
        <link rel="alternate" type="application/rss+xml" title="Jakub Kucharovic weblog" href="{{ url_for('blog.rss') }}">
    </head>
    <body itemscope itemtype="http://schema.org/Blog">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <header class="blog-header" itemprop="name">
                        <h1>
                            <a itemprop="url" href="{{ url_for('blog.index') }}">Jakub Kucharovic</a>
                            <small>weblog</small>
                        </h1>
                    </header>
                </div>
            </div>
            <div class="row">
                <div id="content" class="col-md-9" role="main">
                {% block body %}{% endblock %}
                </div>
                <div id="sidebar" class="col-md-3">
                {% block sidebar %}
                    <aside itemprop="author" itemscope itemtype="http://schema.org/Person">
                        <img src="/assets/img/photo.jpg" class="img-thumbnail" alt="Jakub Kucharovic" itemprop="image">
                        <p>
                            Volám sa <span itemprop="name">Jakub Kucharovic</span>, pracujem ako <span itemprop="jobTitle">webový vývojár</span>
                        </p>
                        <link itemprop="url" href="{{ url_for('homepage') }}">
                        <strong>Kontakty</strong>
                        <ul>
                            <li><a itemprop="sameAs" class="twitter" href="//twitter.com/jkucharovic" title="Účet na Twitter.com">Twitter</a>
                            <li><a itemprop="sameAs" class="github" href="//github.com/kucharovic" title="Účet na GitHub.com">GitHub</a>
                            <li><a itemprop="sameAs" class="stackoverflow" href="//stackoverflow.com/users/1178578/jkucharovic" title="Účet na StackOverflow">StackOverflow</a>
                        </ul>
                    </aside>
                {% endblock %}
                </div>
            </div>
            <footer role="contentinfo">
                &copy; <span itemprop="copyrightHolder" itemscope itemtype="http://schema.org/Person"><span itemprop="name">Jakub Kucharovic</span></span>, <span itemprop="copyrightYear">{{ now.strftime('%Y') }}</span>
            </footer>
        </div>
        {% block javascripts %}
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', '{{ ga_tracking }}', 'auto');
          ga('send', 'pageview');

        </script>
        {% endblock %}
    </body>
</html>

app/templates/blog/show.html
{% extends 'blog/layout.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block description %}{{ post.description }}{% endblock %}

{% block ogp_namespace %}article: http://ogp.me/ns/article#{% endblock %}

{% block meta %}
  <meta property="og:type" content="article">
  <meta property="article:author" content="{{ url_for('homepage', _external=True) }}">
  <meta property="article:published_time" content="{{ post.published_at.isoformat() }}">
  {% if post.modified_at %}
  <meta property="article:modified_time" content="{{ post.modified_at.isoformat() }}">
  {% endif %}
  {% for tag in post.tags %}
  <meta property="article:tag" content="{{ tag }}">
  {% endfor %}
{% endblock %}

{% block body %}
  <article itemprop="blogPost" itemscope itemtype="http://schema.org/BlogPosting">

    <header>
      <h1 itemprop="name headline">{{ self.title() }}</h1>
      <p>
        <time pubdate datetime="{{ post.published_at.isoformat() }}" itemprop="datePublished" title="Zverejnené {{ post.published_at.strftime("%a, %d %b %Y %H:%M:%S") }}">{{ post.published_at.strftime("%a, %d %b %Y %H:%M:%S") }}</time>,
        {% if post.modified_at %}
        <time pubdate datetime="{{ post.modified_at.isoformat() }}" itemprop="dateModified" title="Naposledy upravené {{ post.modified_at.strftime("%a, %d %b %Y %H:%M:%S") }}">{{ post.modified_at.strftime("%a, %d %b %Y %H:%M:%S") }}</time>,
        {% endif %}
        <b>Štítky</b>:
        {% for tag in post.tags %}
            <a href="{{ url_for('blog.tag', slug=tag.slug) }}">{{ tag }}</a>{% if false == loop.last %}, {% endif %}
        {% endfor %}
      </p>
    </header>

    <div class="content" itemprop="articleBody">
    {{ post.perex|safe }}
    {{ post.content|safe }}
    </div>

  </article>

  <p>
    <a href="{{ url_for('blog.index') }}">&larr; Späť na zoznam</a>
  </p>
{% endblock %}

{% block stylesheets %}
  {{ super() }}
  <link rel="stylesheet" href="/assets/css/monokai_sublime.css">
{% endblock %}

{% block javascripts %}
  {{ super() }}
  <script src="/assets/js/highlight.pack.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
{% endblock %}

app/templates/blog/tag.html
{% extends 'blog/layout.html' %}

{% block title %}Zoznam príspevkov označených „{{ tag.title }}“{% endblock %}

{% block body %}
  <h1>{{ self.title() }}</h1>
  {% include 'blog/article_list.html' with context %}
{% endblock %}

app/templates/homepage.html
<!DOCTYPE HTML>
<html itemscope itemtype="http://schema.org/Person" prefix="og: http://ogp.me/ns# profile: http://ogp.me/ns/profile#">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta property="og:title" itemprop="name" content="Jakub Kucharovic">
  <meta itemprop="jobTitle" content="web developer">
  <meta property="og:image" itemprop="image" content="http://kucharovic.sk/assets/img/photo.jpg">
  <meta property="og:url" itemprop="url" content="http://kucharovic.sk/">
  <meta property="og:type" content="profile">
  <meta property="profile:first_name" content="Jakub">
  <meta property="profile:last_name" content="Kucharovic">
  <meta property="profile:gender" itemprop="gender" content="Male">
  <link href="http://www.myopenid.com/server" rel="openid.server">
  <link href="http://kucharovic.myopenid.com" rel="openid.delegate">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet" type="text/css">
  <link href="/assets/css/stylesheet.css" rel="stylesheet" type="text/css">

  <title>Jakub Kucharovic</title>
<body>
  <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
    <meta itemprop="addressLocality" content="Ostrava">
  </div>
  <h1>Jakub Kucharovic</h1>
<p>
  web developer
</p>
<ul class="social-icons">
  <li>
    <a class="social-icon email" href="mailto:jakub&#64;kucharovic.sk" title="E-mailová adresa">
      jakub&#64;kucharovic.sk
    </a>

  <li>
    <a class="social-icon google" href="https://plus.google.com/110283236721497573515?rel=author" title="Profil na Google+">
      Google plus
    </a>

  <li>
    <a class="social-icon twitter" href="http://twitter.com/jkucharovic" title="Účet na Twitter">
      Twitter
    </a>

  <li>
    <a class="social-icon stackoverflow" href="http://stackoverflow.com/users/1178578/jkucharovic" title="Profil na Stackoverflow"> Stackoverflow
    </a>
  <li>
    <a class="social-icon github" href="https://github.com/kucharovic" title="Účet na GitHub">
      GitHub
    </a>
</ul>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '{{ ga_tracking }}', 'auto');
    ga('send', 'pageview');

    for(var i = 0, l = document.links, p = l.length; i < p; i++) l[i].onmouseover = function(){ga('send','event', 'Social', 'Visit', this.className.replace('social-icon ',''))};
  </script>
</body>